### ISSUE TITLE
Questions about the construction of Hyper Meta-Graph.

### ISSUE THREAD

**Issue by Jill5** [Haoran-Young/HMG-CR#2]
According to the paper, the **graph2** only contains the records of _view_ and _buy_, so, will the view record of items that are only viewed but not purchased be added to the **graph2**? Or does the dataset only contain the records of interactions with purchased items? Look forward to your reply. Thank you!

**Comment by Haoran-Young** [comment]
Graph 2 contains the items which are only viewed by users. Graph i  is the subset of Graph i+1. 

Haoran Yang （杨浩然）
PhD Student
DSMI Lab
School of Computer Science 
Faculty of Engineering & IT
University of Technology Sydney 
+86 18390585345
***@***.***
