### ISSUE TITLE
Questions when I am trying to reproduce the result

### ISSUE THREAD

**Issue by SeanYancy** [Haoran-Young/HMG-CR#3]
Dear Authors of HMG-CR:
I am trying to reproduce the SOTA results in the paper. Have you done the ablation experiments on behavior patterns of the users. Like if 1 denote "View", 2 denote "Fav", 3 denotes "cart", 4 denotes "Buy" as chronological order which you mentioned in paper.
The Hyper Graphs should be {4, 14, 124, 1234} right?
Have you done some experiments on like delete one of them
for example,
HGs_1 = {4, 1234}
HGs_2 = {4, 14, 1245}
Cause I found the improvement of adding graphs is very slight, since i want to add pattern "134" for it. Because i think many people  like me will first add to cart then buy the staff

By the way, thank you for your wonderful work！

I can also communicate with Chinese if you wish.

Thank you

**Comment by Haoran-Young** [comment]
No, what I have done is all shown in the paper. 
You should discuss with your supervisors and implement your method to verify your idea through experiments if you have a different opinion. I cannot judge whether your claim is reasonable or not.
Thanks for your interest.
